[config]
environment=development ;development or production OR COMMENT THIS LINE
templatepath=/MVCFramework/views
controlsfile=/MVCFramework/controls.xml
loggingpath=/assets/logging/

[globals]
APP=BM_test
_LOGO=assets/[Your logo].jpg
_APPDIR=https://[(sub)domeinnaam]/
_HOMEPAGE=https://[your client homepage]
_ASSETDIR=https://[(sub)domeinnaam]/assets/
_SALTRAND=[string e.g. long and random. Please more than 32 random generated characters]
_RAND=[integer e.g. random integer]
_MINLEVELTOLOGIN='A' ;'A' means only Administrators can log in - 'U' means there are Administrators and Members that can log in as Users
_WTALLOWED='Y' ;Indicates whether Wire Transfers as alternative to online payments is allowed

;database setup
_DBUSER=[username on your webhost]_user
_DBPASSWORD="[Your user password]"
_DBNAME=[username on your webhost]_[name of your database]_DB ;Do not forget to match ticketingsystem_user to the database in your cPanel
_DBHOST=localhost

;mail setup
_MAILHOST="mail.[hostname].com"
_MAILHOSTPORT=465
_MAILUSERNAME="website@[domeinnaam]"
_MAILPASSWORD="[Your password]"
_MAILTO=website@[domeinnaam]
_MAILTONAME=Test Team
_MAILFROM=info@[domeinnaam]
_MAILFROMNAME=Test
_MAILREPLYTO=team@[domeinnaam client]

;Mollie betalingssysteem setup
_MOLLIECONFIG="test_[your mollie key]" ;replace test_ key with live_key in prd

;Google wallet setup
_WALLETORIGIN=origin of your google wallet e.g. myconcerts.com
_WALLETCREDENTIALS=config/level-nimbus-[.... Your keyfile from Google Wallet .....].json
_WALLETISSUERID=[Your Google Wallet ID]

;Captcha setup
_CAPTCHASITEKEY=[Your key]
_CAPTCHASECRETKEY=[Your key]

;[commands] Uncomment if you want to work with the CommandResolver
;/=\controllers\DefaultCommand
;/firstlogin=\controllers\commands\login\FirstLoginCommand
